kind = "api"
previewPath = "/"
title = "Tic Tac Toe"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "Tic Tac Toe"
paths = ["/"]

[services.development]
run = "PORT=5000 node /home/runner/workspace/server.js"
